### ISSUE TITLE
Feedback for “NumberBox”

### ISSUE THREAD

**Issue by gravitywave2015** [mljar/runmercury-website#12]
I met this error, how to solve? thanks!
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_3960\1434161747.py in <module>
      1 # displays large number in the box with border
----> 2 mr.NumberBox(data=123, title="Large number")

AttributeError: module 'mercury' has no attribute 'NumberBox'

**Comment by pplonski** [comment]
Hi @gravitywave2015,

Have you solved the issue?
