### ISSUE TITLE
Inconsistent Description in Documentation for Note and Numeric Widgets

### ISSUE THREAD

**Issue by ranggakd** [mljar/runmercury-website#16]
I noticed that the description for both the "note" and "numeric" widgets in the documentation is identical: 
> Adds a Markdown note in the sidebar.

Here are the links to the respective documentation pages:
- [Note Widget](https://github.com/mljar/runmercury-website/blob/main/pages/docs/input-widgets/note.mdx)
- [Numeric Widget](https://github.com/mljar/runmercury-website/blob/main/pages/docs/input-widgets/numeric.mdx)

I believe this might be a copy-paste error. I suggest the update of the description for the "numeric" widget to be:
> Creates a numerical input widget in the sidebar for interactive user inputs.

Also minor suggestion to put either the name of the widget (like `App`, `Button`, `Checkbox`, `File`, `Slider` and `Range`) or not at all at their description for consistent documentation.

**Comment by pplonski** [comment]
Good catch @ranggakd! Do you want PR with fix?

**Comment by ranggakd** [comment]
Absolutely, I do and I will. Thanks.

**Comment by pplonski** [comment]
fixed, thanks!
