### ISSUE TITLE
Missing Steps in `Deploy with docker-compose` Documentation

### ISSUE THREAD

**Issue by ranggakd** [mljar/runmercury-website#17]
I was following the [Deploy with docker-compose](https://runmercury.com/docs/docker-compose/) instructions and noticed some missing steps in the [documentation](https://github.com/mljar/runmercury-website/blob/main/pages/docs/docker-compose.mdx).

The `Dockerfile` and `entrypoint.sh`, which are required in the process, are originally located in this repository: [mljar/mercury](https://github.com/mljar/mercury/tree/main/docker/mercury). However, they are **not mentioned in the documentation** nor **available in the simple demo repository** [mercury-deploy-demo](https://github.com/mljar/mercury-deploy-demo) provided.

I would like to _update the documentation to include these steps_ or _add the necessary files to the demo repository_ whichever makes a better step.

Thank you for your attention to this matter.

**Comment by pplonski** [comment]
Here is docs for Mercury https://github.com/mljar/runmercury-website

**Comment by ranggakd** [comment]
Apparently I was missing one step beforehand therefore I closed this issue immediately
